/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CertificationsIndexRouteImport } from './routes/certifications.index'
import { Route as ExamSlugRouteImport } from './routes/exam.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as CertificationsSlugRouteImport } from './routes/certifications.$slug'
import { Route as CertificateSlugNameRouteImport } from './routes/certificate.$slug.$name'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CertificationsIndexRoute = CertificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CertificationsRoute,
} as any)
const ExamSlugRoute = ExamSlugRouteImport.update({
  id: '/exam/$slug',
  path: '/exam/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsSlugRoute = CertificationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CertificationsRoute,
} as any)
const CertificateSlugNameRoute = CertificateSlugNameRouteImport.update({
  id: '/certificate/$slug/$name',
  path: '/certificate/$slug/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/certificate/$slug/$name': typeof CertificateSlugNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/certifications': typeof CertificationsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/certificate/$slug/$name': typeof CertificateSlugNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/certifications/$slug': typeof CertificationsSlugRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exam/$slug': typeof ExamSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/certificate/$slug/$name': typeof CertificateSlugNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certifications'
    | '/courses'
    | '/pricing'
    | '/certifications/$slug'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/exam/$slug'
    | '/certifications/'
    | '/courses/'
    | '/certificate/$slug/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/certifications/$slug'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/exam/$slug'
    | '/certifications'
    | '/courses'
    | '/certificate/$slug/$name'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/courses'
    | '/pricing'
    | '/certifications/$slug'
    | '/checkout/$slug'
    | '/courses/$slug'
    | '/exam/$slug'
    | '/certifications/'
    | '/courses/'
    | '/certificate/$slug/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationsRoute: typeof CertificationsRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  PricingRoute: typeof PricingRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  ExamSlugRoute: typeof ExamSlugRoute
  CertificateSlugNameRoute: typeof CertificateSlugNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/certifications/': {
      id: '/certifications/'
      path: '/'
      fullPath: '/certifications/'
      preLoaderRoute: typeof CertificationsIndexRouteImport
      parentRoute: typeof CertificationsRoute
    }
    '/exam/$slug': {
      id: '/exam/$slug'
      path: '/exam/$slug'
      fullPath: '/exam/$slug'
      preLoaderRoute: typeof ExamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$slug': {
      id: '/certifications/$slug'
      path: '/$slug'
      fullPath: '/certifications/$slug'
      preLoaderRoute: typeof CertificationsSlugRouteImport
      parentRoute: typeof CertificationsRoute
    }
    '/certificate/$slug/$name': {
      id: '/certificate/$slug/$name'
      path: '/certificate/$slug/$name'
      fullPath: '/certificate/$slug/$name'
      preLoaderRoute: typeof CertificateSlugNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CertificationsRouteChildren {
  CertificationsSlugRoute: typeof CertificationsSlugRoute
  CertificationsIndexRoute: typeof CertificationsIndexRoute
}

const CertificationsRouteChildren: CertificationsRouteChildren = {
  CertificationsSlugRoute: CertificationsSlugRoute,
  CertificationsIndexRoute: CertificationsIndexRoute,
}

const CertificationsRouteWithChildren = CertificationsRoute._addFileChildren(
  CertificationsRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationsRoute: CertificationsRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  PricingRoute: PricingRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  ExamSlugRoute: ExamSlugRoute,
  CertificateSlugNameRoute: CertificateSlugNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
